server:
  port: 9999
spring:
  application:
    name: "@artifactId@"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-client
          uri: lb://product-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/product/**

        - id: inoutStore-client
          uri: lb://inoutStore-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/inoutStore/**

        - id: user-client
          uri: lb://user-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/user/**
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
