server:
  port: 9999
spring:
  application:
    name: "@artifactId@"
  profiles:
    active: k8s
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-client
          uri: lb://product-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/product/**

        - id: inoutStore-client
          uri: lb://inoutStore-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/inoutStore/**

        - id: user-client
          uri: lb://user-client
          filters:
            - StripPrefix=1
          predicates:
            - Path=/user/**
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: true
    fetch-registry: true
